services:
  - type: web
    name: agendi
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CANVAS_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
